### ISSUE TITLE
community.kubernetes.k8s Ansible module not working

### ISSUE THREAD

**Issue by sergioagm** [book-of-kubernetes/examples#1]
Hi, first of all, great book! I just started reading it and I'm liking it so far.

When I tried to create the vm with Vagrant for chapter-01, I ran into an issue during the Ansible provisioner:

```
$ vagrant up
...
==> host01: Running provisioner: ansible...
    host01: Running ansible-playbook...
ERROR! couldn't resolve module/action 'community.kubernetes.k8s'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '~/dev/examples/setup/roles/todo/tasks/main.yaml': line 11, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
```

I'm not familiar with Ansible but I fixed it by going to the  `setup/roles/todo/tasks/main.yaml` and replacing the collection  `community.kubernetes.k8s:` to `kubernetes.core.k8s:`. I'm guessing that line also has to be changed in other roles. I changed it based on the message here: https://galaxy.ansible.com/community/kubernetes

I'm using Fedora 36 with Ansible 2.13.2.

I also replaced the virtualbox provider in Vagrant with libvirt and everything is working correctly. I can see the to-do app running.

**Comment by AlanHohn** [comment]
Thanks for catching this and writing up the issue! That action moved midway through writing the book and I neglected to backport it to the early access content. Sorry for the inconvenience. We're close enough to the release date so I went ahead and loaded the rest of the example content, which should fix this issue as well as a few others we uncovered while finishing up testing.

Great to hear that it works with the `libvirt` Vagrant provider.
