### ISSUE TITLE
Kubectl not working in new vagrant environment 

### ISSUE THREAD

**Issue by RubenMakandra** [book-of-kubernetes/examples#15]
## Expected Behavior
`kubectl` can be used in a freshly set up vagrant environment

## Current Behavior
Starting in Chapter 6 I get the error `The connection to the server localhost:8080 was refused - did you specify the right host or port?` when I try to use any `kubectl` commands.

## Possible Solution
I could get kubectl running by using `cp -i /etc/kubernetes/admin.conf /root/.kube/config` to copy the config file to `/root/.kube/`
Command found [here](https://discuss.kubernetes.io/t/the-connection-to-the-server-localhost-8080-was-refused-did-you-specify-the-right-host-or-port/1464)

## Steps to Reproduce
1. `vagrant up`
2. `vagrant ssh host01`
3. `sudo su `
4. `kubectl get pods`

## Context (Environment)
**OS:** `Ubuntu`
**Version:** `20.04.5 LTS (Focal Fossa)`
**Ansible core version:** `2.13.7` (installed via `pip`, since the official apt ansible 2.9.6 package failed to execute some of the previous play books)
**Vagrant version**: `2.3.4`

## Detailed Description
The Issue appeared consistently for me, even when destroying and re-provisioning the environment. The `vagrant up` command to create the environments finished successfully.  
The issue appeared first in chapter 6, up to chapter 8. Since I didn't progress further I can't say if it also affects all the chapters after. The /root/.kube/ directory only contained a directory named `cache` and nothing else before I copied the config.
Edit: The $KUBECONFIG environment variable is empty, which explains the error.

**Comment by AlanHohn** [comment]
If you add a hyphen `-` to the end of the `sudo` command it should pick up the correct `KUBECONFIG` variable.

Unfortunately, when you run `sudo su` without the hyphen `-` you are still operating with the environment of the `vagrant` user.

Apologies for the issue and for the pickiness of the command. I may try to think of a way to simplify that. If you have any ideas please share.

**Comment by RubenMakandra** [comment]
Thanks for the solution, somehow I totally missed the hyphen at the end.

An alternative could be `sudo -i`, it worked for me in the couple chapters I tried it out, but since it's not doing exactly the same as `sudo su - ` it might not be suitable for all chapters.
