### ISSUE TITLE
Contents of chapter-12/containerd/files/node-evict.yaml is different from the book

### ISSUE THREAD

**Issue by jcaberio** [book-of-kubernetes/examples#16]
https://github.com/book-of-kubernetes/examples/blob/bfe7a577b69b102de4da31b452bdc83edf9a3b61/chapter-12/containerd/files/node-evict.yaml#L2

![Polish_20230131_230705378 1](https://user-images.githubusercontent.com/21195237/215798034-0a2de1c4-973d-490f-a74d-dbf3eb4addaf.jpg)

**Comment by AlanHohn** [comment]
Thanks! Great catch. Appreciate the PR.
