### ISSUE TITLE
Missing link / footnote

### ISSUE THREAD

**Issue by abe-101** [book-of-kubernetes/examples#19]
The Readme in the setup intends to provide a link to install the latest version of vagrant

https://github.com/book-of-kubernetes/examples/blob/ac353a13c74f94208d6fb06162440b5d5a6ca45a/setup/README.md?plain=1#L148

But there is no link just a footnote that leads nowhere

**Comment by abe-101** [comment]
I'd assume the correct link is to https://developer.hashicorp.com/vagrant/downloads
If that is the case I'd be happy to open a PR

**Comment by abe-101** [comment]
I should note that in order to get the setup working on my machine (fedora 37) It was not enough to use the version of `vagrant` that was install by the fedora repos (Vagrant 2.2.19) 
I instead removed it and added the hashicorp repos which allowed me to get the latest version (Vagrant 2.3.4)

**Comment by AlanHohn** [comment]
Ugh, I really meant to write actual Vagrant instructions, not just leave a placeholder with some random notes from back when I was writing the book. I've written those up now. Thanks for the note about Fedora; I've incorporated it. By all means please reach out to me if you notice that I've written something wrong or if you have other issues.
