### ISSUE TITLE
Calico download URL broken.

### ISSUE THREAD

**Issue by crigertg** [book-of-kubernetes/examples#20]
The URL `https://docs.projectcalico.org/archive/` returns a 404. The [documentation](https://docs.tigera.io/archive/v3.22/getting-started/kubernetes/quickstart) now refers a different URL: `https://projectcalico.docs.tigera.io/archive/`

I've provided a PR: https://github.com/book-of-kubernetes/examples/pull/18

**Comment by AlanHohn** [comment]
Thanks!
