### ISSUE TITLE
Directory structure in chapters 8 & 12 is causing playbook.yaml to fail

### ISSUE THREAD

**Issue by kevope** [book-of-kubernetes/examples#9]
I keep getting 'unreachable' errors when I run the playbooks from inside their respective directories in chapters 8 & 12. The aws-setup playbook works but it looks like Ansible is having an issue with the relative path to the ssh keys. This is the error that I get:

`/examples/chapter-12/containerd/../sshkeys/id_rsa_aws_ansible_k8s: No such file or directory`

The aws-ssh.sh script also fails, throwing this warning:
`Warning: Identity file ../sshkeys/id_rsa_aws_ansible_k8s not accessible: No such file or directory.`

However, I've gotten the ssh script to run by manually changing the ssh_args from `../sshkeys/id_rsa_aws_ansible_k8s` to `../../sshkeys/id_rsa_aws_ansible_k8s`  

I'm pretty sure that path just needs to be updated since it's being run from inside a nested directory. The weird part is that the ansible.cfg inside the nested directories uses the correct, ../../, file paths. So I'm assuming there is something else that is hard coding that path somewhere but I'm not familiar enough with Ansible to fix it.   

I might just be overthinking it but I wanted to bring this up because I didn't see anything mentioned in the READMEs or in the setup directory. 

That said, I still got it to work by copying all of the files in the nested directory into the chapter directory and changing the relative file paths inside the ansible.cfg file from '../../' to just '../'

**Comment by AlanHohn** [comment]
Thanks so much for putting in this issue! This was definitely a mistake on my part, not testing the AWS automation as thoroughly as the Vagrant automation.

In addition to the template that generates the `aws-ssh.sh` script, the setting that was messing up the playbook was hiding in `setup/ec2-inventory`. That directory has configuration that generates the Ansible inventory dynamically based on the instances that were created in EC2. It also sets some variables for connecting to those instances, including the location of the SSH private key file. I was able to change it to find the private key based on the `inventory_dir`, which is constant even for chapters with subdirectories.

Thanks again for filing the issue and helping me quickly get to a fix. Sorry for the inconvenience and I hope you're enjoying the book.
